### ISSUE TITLE
API for TempFly?

### ISSUE THREAD

**Issue by SuixideBunneh** [ChiefMoneyBags/TempFly#1]
Hello,

How can I use your plugin as an API for my own plugin? Basically, I want to get the flight time available for the player, whether in "time format" or permanent format.

Float timeFly = TempFly.plugin. ...[where can I pull the data from?]

Thanks

**Comment by ChiefMoneyBags** [comment]
I will add a dedicated Tempfly API class

**Comment by ChiefMoneyBags** [comment]
Tempfly.getAPI()
