### ISSUE TITLE
TempFly and PhantomCombat incompatibility

### ISSUE THREAD

**Issue by PoeticRainbow** [ChiefMoneyBags/TempFly#10]
When having both [TempFly](https://github.com/ChiefMoneyBags/TempFly) and [PhantomCombat](https://github.com/lokka30/PhantomCombat) installed, both which have options to disable flight on combat, after engaging in combat, you cannot turn your fly off. I think this is due to both plugins trying to re-enable flight after the combat is over. I really like the system in PhantomCombat, but I also love the concept of TempFly for my server; so I would really enjoy having both compatible. This issue occurs even with only one of the flight-disabling modules enabled.
I'm reporting to both repositories because I'm not sure which one would have to implement a fix. Thank you so much.
[[Other Issue]](https://github.com/lokka30/PhantomCombat/issues/66)

**Comment by ChiefMoneyBags** [comment]
Which version of tempfly do you have installed.

**Comment by PoeticRainbow** [comment]
TempFly 2.0.8, installed on Paper Build #134 (1.16.1)

**Comment by ChiefMoneyBags** [comment]
ok, Can you see if your issue persists with this version, its a 3.0.0 beta version. i haven't released it on spigot yet. [https://drive.google.com/file/d/1Jp-sK08U_0kA45KWQ4p_ftzXsxs-bott/view?usp=sharing](url)

**Comment by ChiefMoneyBags** [comment]
I am thinking the issue may be a bug in version 2.0.8 and not a confliction. If the issue still persists i will work with Lokka30 to fix the confliction.

**Comment by PoeticRainbow** [comment]
This new version didn't fix the issue sadly. When I attack a mob, I drop to the ground, but then I am able to fly right after while PhantomCombat tells me "You can't fly in combat mode" over and over again.
I've figured out that the issue only occurs if you are flying when you first hit the mob, so if you were already not flying when fighting the mob, it works as intended.

**Comment by ChiefMoneyBags** [comment]
ok i will see what i can do.

**Comment by PoeticRainbow** [comment]
Thank you

**Comment by ChiefMoneyBags** [comment]
Try this. [https://drive.google.com/file/d/1tUh11KwFcQKBwRCIxciUJIB5QBIzxh4v/view?usp=sharing](url)

**Comment by ChiefMoneyBags** [comment]
I tested this it works on my server with the default phantomcombat config. If there are no issues i will make a pull request for phantomcombat to fix it.

**Comment by PoeticRainbow** [comment]
It works amazingly! Thank you so much!

**Comment by ChiefMoneyBags** [comment]
Your welcome

**Comment by ChiefMoneyBags** [comment]
Just wanted to give a heads up you will need to re download phantom combat if you remove TempFly from your server. I just noticied the version i sent you will break without TempFly on the server. I put a fix in the version here though if you want it. [https://drive.google.com/file/d/1tUh11KwFcQKBwRCIxciUJIB5QBIzxh4v/view](url)
