### ISSUE TITLE
[Bug] Bypass perm still shows "You may now fly again" messages

### ISSUE THREAD

**Issue by JasonHorkles** [ChiefMoneyBags/TempFly#11]
If you have the perm to bypass the no-fly areas, it'll show the message saying you can fly again when you exit the region
Version 3.0.0

**Comment by ChiefMoneyBags** [comment]
I can not reproduce this bug, can you give me the steps i must take to trigger it? https://gyazo.com/8c2c7f59471ce610763a63df74a77ebf

**Comment by ChiefMoneyBags** [comment]
Nevermind i fiigured it out. It happens when you do not have flight enabled. It still tries to auto enable the players flight when they do not have any more flight requirements even though they are in bypass mode. I will fix it for you.

**Comment by JasonHorkles** [comment]
Sweet!
Also, it seems like bypass and a few other sub-commands don't tab complete, including the normal `/fly` (it just shows up as red and I have to use commands.yml to manually make it appear, even though I have `fly_override_permissions: []`
Is it possible to fix this?
Thanks so much!

**Comment by ChiefMoneyBags** [comment]
I completely forgot about the tab completer and just started adding commands. I guess i forgot to update /tf help as well. I need to add the commands into the tab completer.

**Comment by ChiefMoneyBags** [comment]
I'm going to just throw the new sub command bases into the tab completer for now but i want to spend a few hours coming up with a good looking new tab completer system sometime soon. I want it it to complete the proper arguments and time units correctly depending on where they are in the command instead of just completing the first argument.

**Comment by ChiefMoneyBags** [comment]
https://drive.google.com/file/d/1Jp-sK08U_0kA45KWQ4p_ftzXsxs-bott/view?usp=sharing
