### ISSUE TITLE
Errors on startup and command use

### ISSUE THREAD

**Issue by JasonHorkles** [ChiefMoneyBags/TempFly#14]
https://pastebin.com/f3tWns8S with the latest build on spigot published today

**Comment by JasonHorkles** [comment]
Also this was with a fresh version of TempFly, default config and everything

**Comment by JasonHorkles** [comment]
Fixed in hotfix, thanks

**Comment by JasonHorkles** [comment]
Wait nvm now I got this error after joining lol
https://pastebin.com/Dd4CkpXW

Edit: it seems to only happen on one account, is there some data that might be corrupted?

**Comment by ChiefMoneyBags** [comment]
I'm sorry I haven't been looking at the github issues and just saw your post. I will look into the issue.

**Comment by ChiefMoneyBags** [comment]
Can you enable debug in the config and show me the log when the account joins and the error happens?

**Comment by ChiefMoneyBags** [comment]
It should happen if you log into the server in a worldguard region that force updates a players gamemode with the game-mode flag. I havent gotten the error to occur however.

**Comment by JasonHorkles** [comment]
https://hasteb.in/rixugelo.shell
it may be because I also have a WorldGuard flag set to teleport to a certain location in the region when they rejoin?

**Comment by JasonHorkles** [comment]
Yeah ok so it seems to happen if you have fly set to be disabled in the region (with the WorldGuardExtraFlags flag) along with the join-location flag (also a WGEF flag) set

**Comment by ChiefMoneyBags** [comment]
Ok that's kinda strange. WorldGuard is teleporting the player before they have technically joined the server so tempfly isn't ready and doesn't have the players data loaded yet. i will think about how to fix it.

**Comment by JasonHorkles** [comment]
it may also help to note that this didn't happen with the older tempfly version (the ones before the larger update a few days ago)

**Comment by ChiefMoneyBags** [comment]
i know because i made a bunch of stuff async to help performance and it made everything a lot more complicated.

**Comment by ChiefMoneyBags** [comment]
i see this message in the log "------------ On PlayerjOIN event ------------" but is this one present? "------------ On AsyncPlayerPreLogin event ------------"

**Comment by JasonHorkles** [comment]
yes that appears after enabling the debug and reloading the plugin

**Comment by ChiefMoneyBags** [comment]
is it above the error

**Comment by JasonHorkles** [comment]
yes - at least above the error i got after turning debug on

**Comment by ChiefMoneyBags** [comment]
can you try this [https://drive.google.com/file/d/17ab7VVahWY7K9Wgk1UoTsH3oNwzMIuUB/view?usp=sharing](url)

**Comment by JasonHorkles** [comment]
seems to work fine, thanks!

**Comment by JasonHorkles** [comment]
it looks like flight is now being automatically activated in disabled regions when they join, however
but the errors don't occur anymore

if the player isn't in any region it works just fine

**Comment by ChiefMoneyBags** [comment]
Is the flight disabled in tempfly or worldguard

**Comment by JasonHorkles** [comment]
tempfly
if disabled with worldguard and tempfly the same issue occurs, except they just can't double jump to actually start flying

**Comment by ChiefMoneyBags** [comment]
are you sure this wasn't a bug before, i found the problem but it is something i haven't touched in months. I think this has been a thing and nobody has noticed lol.

**Comment by JasonHorkles** [comment]
that's possible, but i've definitely not noticed it before

**Comment by ChiefMoneyBags** [comment]
i posted an update

**Comment by JasonHorkles** [comment]
Seems to happen still with the worldguard region teleporting them on join
https://pastebin.com/0q6N8guX
