### ISSUE TITLE
Error while attempting /tempfly trail

### ISSUE THREAD

**Issue by JustJP2K** [ChiefMoneyBags/TempFly#20]
07.01 10:32:34 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tfly' in plugin TempFly v3.0.6
07.01 10:32:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1257) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-386]
07.01 10:32:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
07.01 10:32:34 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
07.01 10:32:34 [Server] INFO at com.moneybags.tempfly.command.admin.CmdTrailSet.executeAs(CmdTrailSet.java:62) ~[?:?]
07.01 10:32:34 [Server] INFO at com.moneybags.tempfly.command.TempFlyExecutor.onCommand(TempFlyExecutor.java:30) ~[?:?]
07.01 10:32:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-386]

**Comment by ChiefMoneyBags** [comment]
fixed

**Comment by JustJP2K** [comment]
> 
> 
> fixed

will it get uploaded to spigot or where could i download the newest file?
