### ISSUE TITLE
WorldGuard join-location errors

### ISSUE THREAD

**Issue by JasonHorkles** [ChiefMoneyBags/TempFly#23]
Same as the last comment on #14 
https://pastebin.com/0q6N8guX

**Comment by ChiefMoneyBags** [comment]
Can you test this version, iv'e changed stuff since the last version you had and i would like to see if the problem persists, and if so i need the new stack trace [https://drive.google.com/file/d/1pUC0-1JdvMKwFOlZ71H6nbSW_qAWexta/view?usp=sharing](url)

**Comment by JasonHorkles** [comment]
alright looks like it does work properly in that build
