### ISSUE TITLE
TempFly 1.9.2 still no API

### ISSUE THREAD

**Issue by SuixideBunneh** [ChiefMoneyBags/TempFly#3]
Hello,

I tried version 1.9.2 but Tempfly.getAPI() is still not available. I also do not see the changes you made on the new version 1.9.2 in Spigot. 

```
public static TempFlyAPI getAPI() {
		return tfApi;
	}

```
I do not see this in the latest Jar. Can you recheck? Thank you.

**Comment by ChiefMoneyBags** [comment]
I posted an update. I tried to just replace the old jar with the new one without posting an update on spigot but i guess that doesn't work.
