### ISSUE TITLE
"You may now fly again" message when leaving anything blocked

### ISSUE THREAD

**Issue by JasonHorkles** [ChiefMoneyBags/TempFly#34]
TF 3.0.9
Paper-484 1.16.5
When leaving a blacklisted world, region, etc, the message saying you may fly again is sent even if you weren't flying
This also happens when changing gamemodes

**Comment by ChiefMoneyBags** [comment]
I know what the problem is.

**Comment by ChiefMoneyBags** [comment]
I fixed it but i think i'm going to add some more stuff before i post an update.
