### ISSUE TITLE
Console error with command /tf trail <player> & feature request // question

### ISSUE THREAD

**Issue by USBCharger** [ChiefMoneyBags/TempFly#36]
Hey, so first off, I wanted to say thank you **so much** for making this wonderful plugin. I've looked everywhere and couldn't find any good fly plugins, and yours covers literally **everything** I want and more as essentials.. well... it just really doesn't cut it for me.
First off, when I was running the /tf trail <player> I got this error. [https://pastebin.com/eYJzPaVg](https://pastebin.com/eYJzPaVg)
Secondly, I'd like to make a feature request: most of the chat output from the plugin is able to be customized, however I've found that the fly speed command, which I intend to use on my server a lot, gives you a syntax that doesn't appear to be editable.  [https://imgur.com/a/lHDe5jG](https://imgur.com/a/lHDe5jG) EDIT: I've also noticed the command does not give you a permissions error when you do /tf speed unless you put in a number, and only gives you that syntax as shown in the screenshot.
Finally, I wanted to ask if it was possible through permissions to have the maximum fly speed be a decimal, such as 2.5 for one rank and 5 for another, and if so, how. I've tried tempfly.speed.2.5 and it just gives me 2... which is understandable, as that's supposed to be where another permission syntax thing is (if that's what they're called) but I was just wondering if it was possible to set up decimals with permissions.
Thanks, and have a nice day, 
~Rocket

**Comment by ChiefMoneyBags** [comment]
I fixed the decimal permission for speed and the tf trail error. I will make the command syntax configurable in the next update.
