### ISSUE TITLE
"You may now fly again" after killing mobs and exiting regions when not flying

### ISSUE THREAD

**Issue by JasonHorkles** [ChiefMoneyBags/TempFly#38]
If you're not flying, the plugin will still say that you can fly again when the mob killing cooldown ends or if you exit a region where it's disabled. I'd imagine it should only send that message when the player is actually flying

**Comment by ChiefMoneyBags** [comment]
Is it fixed for you in 3.1.0

**Comment by JasonHorkles** [comment]
It is, thanks!
