### ISSUE TITLE
Flight Auto Enables on Teleport when it Shouldn't

### ISSUE THREAD

**Issue by Strahilchu** [ChiefMoneyBags/TempFly#42]
When a player does /Tfly and DISABLES flight, if they /rtp or /warp their flight is automatically enabled.

Notice below that auto_enable is FALSE

Yet the plugin still auto enables flight.

Relevant config section:
  flight:
    # Set the default maximum speed players can fly unless otherwise specified by the tempfly.speed.[speed] permission.
    # This does not automatically set the speed to this number unless it is set below 1. (decimals are valid)
    default_speed: 3
    # The maximum y level a player can reach before flight is disabled.
    maximum_height: 400
    # If true a user will start flying again when they no longer have flight requirements so long as their flight is enabled.
    # Example;
    # - A user flies into a disabled region and loses flight.
    # - If auto_fly is true they will fly again automatically without needing to use the fly command.
    auto_enable: false

**Comment by ChiefMoneyBags** [comment]
Thanks I will check it out
