### ISSUE TITLE
ActionBar don't Work -> Console Warning !!

### ISSUE THREAD

**Issue by Ninatasia** [ChiefMoneyBags/TempFly#43]
Hi! I've a big warning on my console and the Aesthetic ActionBar for the remaining time of TempFly don't work and not showing on my server.

My console warning : https://paste.lucko.me/NLeGmxzpT7

Have a good day!

**Comment by ChiefMoneyBags** [comment]
What version of tempfly and minecraft are you running?

**Comment by Ninatasia** [comment]
Plugin: Last version
Serveur: Purpur 1.17.1

**Comment by ChiefMoneyBags** [comment]
Ok I will check it out.

**Comment by Ninatasia** [comment]
Okay thx u very much
