### ISSUE TITLE
Potential memory leak in DataBridge.java

### ISSUE THREAD

**Issue by banicola** [ChiefMoneyBags/TempFly#44]
Hi,

It has been a few weeks now, maybe when I went from 1.16.5 to 1.17.1 that I get tps drop every day around 12 hours after a restart. I finally had the opportunity to take a look at the memory heap with Eclipse Memory Analyser which has a feature to find memory leaks and it revealed an issue in with a thread generated by **tempfly/util/data/DataBridge.java.**

Specifically it is an issue with the usage of **ConcurrentHashMap**.

I removed the plugin this morning and we have experienced tps drop for the first time in weeks.

Details:
Server version: Tunity 1.17.1
Plugin version 3.1.0

**Comment by ChiefMoneyBags** [comment]
I removed the data bridge thread and replaced it with an executor service.
