### ISSUE TITLE
Tempfly Shop issue

### ISSUE THREAD

**Issue by Deadfaerytale** [ChiefMoneyBags/TempFly#5]
Hi, the tempfly shop does not sync with the config file.
I set the Fly shop to true, and I made changes to the pricing. 
However, when I reload the plugin, the shop does not update to the change in the config

**Comment by ChiefMoneyBags** [comment]
I forgot to add the shop to the reload command. I will fix this soon

**Comment by ChiefMoneyBags** [comment]
It should work fine on server restart until then.

**Comment by Deadfaerytale** [comment]
ohhhh ok xDD  tyy
