### ISSUE TITLE
Console Error with TempFly and Iridium Skyblock

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [ChiefMoneyBags/TempFly#51]
latest.log: https://pastebin.com/0JmhVkYh
/Version: git-Purpur-1566 (MC: 1.18.1)
/plugins:
Plugins (57): AdvancedCrates, AuctionHouse, BankPlus, BCommons*, ChatReaction, Citizens, ClearLag, CMILib, CoreProtect, CraftingStore, DeluxeMenus, DeluxeTags, eGlow, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), FeatherBoard, HolographicDisplays, HolographicExtension, InteractionVisualizer, InteractiveChat, IridiumSkyblock, Jobs, LiteBans, LuckPerms, MoneyPrinters, Multiverse-Core*, MVdWPlaceholderAPI*, NoRainReloaded*, OldCombatMechanics, Parties, PhantixCore, PlaceholderAPI, PlayerPoints, PlayerVaults*, PlugManX (PlugMan), ProtocolLib, RoseStacker, Sellwand, ServerListPlus*, ShopGUIPlus, SilkSpawners, SimplePets, TAB-Bridge, TempFly, TimedRewards, TimeIsMoney, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, Votifier, VotingPlugin, Vouchers, WorldGuard

Could you please tell me what is causing the console error or could you fix the issue? Thank you! :)

**Comment by ChiefMoneyBags** [comment]
The current version of TempFly does not support hooking into your version of IridiumSkyblock. The TempFly error is unfortunately not what is causing your larger issue regarding island regeneration. The error simply means that TempFly is trying to ask IridiumSkyblock if a specific world is an island world as it wants to check flight restrictions in that island world. The method to do so in recent versions of IridiumSkyblock has changed so TempFly errors as it does not know what to do. You can prevent the TempFly error by navigating to the skyblock config file located in TempFly/hooks/SkyBlock/IridiumSkyblock.yml and set the value "enable_hook" to false.
