### ISSUE TITLE
A couple players on my server are having issues with TempFly placeholders working/causing console spam

### ISSUE THREAD

**Issue by Azakaturan** [ChiefMoneyBags/TempFly#52]
A couple users on my server are causing an error with TempFly placeholders whenever they teleport.  I can get it to stop spamming if I reload TitleManager until they teleport again.  The error is below:

![image](https://user-images.githubusercontent.com/79327162/161403046-562758fc-520d-4e5d-a1a3-a706313163fa.png)

Then it starts spamming:

![image](https://user-images.githubusercontent.com/79327162/161403054-b2f2a2b8-5519-4c24-babc-ff580cf31f80.png)

Until I reload TitleManager again.  

I am using version 3.1.4

**Comment by ChiefMoneyBags** [comment]
Do the players experience any other problems using tempfly when they teleport or is it only the placeholders?

**Comment by Azakaturan** [comment]
> Do the players experience any other problems using tempfly when they teleport or is it only the placeholders?

The one person I know for sure has infinite fly (we have a token buying system) so they don't use temp fly.  Other people have infinite fly though with no issues.  The name does start with a number though?  Maybe that is screwing with something.

**Comment by Azakaturan** [comment]
> Do the players experience any other problems using tempfly when they teleport or is it only the placeholders?

After that started, other placeholder issues were coming up, and after some investigating it ended up being the Quests placeholders breaking and causing issues all over the place, so you can probably close this.

**Comment by ChiefMoneyBags** [comment]
Alright thanks for the info! Let me know if you experience any more issues.

**Comment by Azakaturan** [comment]
> Alright thanks for the info! Let me know if you experience any more issues.

Mmm sorry, it actually *wasn't* related to the quests placeholders breaking :(

![image](https://user-images.githubusercontent.com/79327162/161617983-a64b933c-8019-44b4-a574-764f60ea8766.png)

This is the only player it breaks for, it might be because their name starts with a number?  I'm not sure.  They have infinite fly, as does a number of other players and this is the only person it breaks for.  I actually have 0 idea of what triggers it.  Looking at the logs they were going to homes and stuff all morning, then TempFly just decided their username wasn't good randomly.

**Comment by ChiefMoneyBags** [comment]
Are there any errors from tempfly when the player joins?

**Comment by Azakaturan** [comment]
No, there's no errors or anything when they login.

**Comment by Azakaturan** [comment]
> Are there any errors from tempfly when the player joins?

So they were going to player warps, etc fine with no errors.  The only time the error started is after the first time they did a /home.

**Comment by ChiefMoneyBags** [comment]
I can make a quick fix to stop the console spam but it will not fix the root issue causing the placeholder to break. I will need to do more digging to find what is causing the issue.

**Comment by Azakaturan** [comment]
It might be when they go to a home in another world, but I'd have to wait until they are online before I could test it.

**Comment by ChiefMoneyBags** [comment]
do you have any kind of plugin that enables per world plugins? For example a plugin that makes multiple worlds appear to be multiple servers on a network to players, but in reality its just one server?

**Comment by ChiefMoneyBags** [comment]
Also i got called into work just now so i will need to put your issue off until tomorrow, i'm sorry.

**Comment by Azakaturan** [comment]
It's fine, and no I just use bungee and multiverse.

**Comment by ChiefMoneyBags** [comment]
ok
