### ISSUE TITLE
PlaceHolderAPI not working

### ISSUE THREAD

**Issue by Fredthedoggy** [ChiefMoneyBags/TempFly#8]
![javaw_O3DgyZLWkH](https://user-images.githubusercontent.com/45927799/81975001-6490ee00-95f4-11ea-81d4-95e38ade5a2f.png)
Placeholder API does not seem to work. Is there a specific Expansion I need?

**Comment by ChiefMoneyBags** [comment]
An expansion is not required for placeholder to work, they are built into the plugin. Try with the new update if you are still interested in this issue.
