### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JasonHorkles** [ChiefMoneyBags/TempFly#9]
It'd be nice if there was 1: a perm to bypass not being able to fly in a world/region, and 2: a way for it to check the fly perms on world change so if they lose the perms when switching worlds then it'll turn off their fly
Thanks!

**Comment by ChiefMoneyBags** [comment]
I will add it

**Comment by JasonHorkles** [comment]
Was
> check the fly perms on world change so if they lose the perms when switching worlds then it'll turn off their fly

also added because it doesn't seem to do it with the jar you sent yesterday in #11

**Comment by JasonHorkles** [comment]
I could also add it to a new issue if you'd like
